const state = { entries: [], mode: 'literal', preferEnglish: true, sortColumn: 'original', sortDirection: 'ascending' };
const categoryCodes = { Noun: 'N', ProperNoun: 'PN', Pronoun: 'PRN', Adjective: 'ADJ', Adverb: 'ADV', Article: 'ART', Determiner: 'D', Preposition: 'PRP', Conjunction: 'C', Interjection: 'I', Numeral: 'NM', Particle: 'PRT', Verb: 'V' };
const input = document.querySelector('#search-input');
const entriesElement = document.querySelector('#entries');
const emptyState = document.querySelector('#empty-state');
const searchStatus = document.querySelector('#search-status');
const datasetStatus = document.querySelector('#dataset-status');
const statusDot = document.querySelector('.status-dot');
const copyToast = document.querySelector('#copy-toast');
const searchHistoryElement = document.querySelector('#search-history');
const searchHistoryKey = 'milim_history';
let searchHistory = [];
let lastTouchTime = 0;
let lastTouchRow = null;
let suppressClickUntil = 0;

function renderSearchHistory() { searchHistoryElement.replaceChildren(...searchHistory.map((term) => { const option = document.createElement('option'); option.value = term; return option; })); }
function loadSearchHistory() { try { const stored = JSON.parse(localStorage.getItem(searchHistoryKey) || '[]'); searchHistory = Array.isArray(stored) ? stored.filter((term) => typeof term === 'string' && term.trim()).slice(-50) : []; } catch { searchHistory = []; } renderSearchHistory(); }
function saveSearchTerm(value) { const term = value.trim(); if (!term || searchHistory.includes(term)) return; searchHistory = [...searchHistory, term].slice(-50); try { localStorage.setItem(searchHistoryKey, JSON.stringify(searchHistory)); } catch { return; } renderSearchHistory(); }
function fold(value) { return String(value || '').toLocaleLowerCase().normalize('NFD').replace(/\p{M}/gu, ''); }
function containsHebrewLetter(value) { return /[\u0590-\u05ff\uFB1D-\uFB4F]/u.test(value); }
function damerau(source, target, limit) { let previousPrevious = Array(target.length + 1).fill(0); let previous = Array.from({ length: target.length + 1 }, (_, index) => index); let current = Array(target.length + 1).fill(0); for (let sourceIndex = 1; sourceIndex <= source.length; sourceIndex += 1) { current[0] = sourceIndex; let rowMinimum = current[0]; for (let targetIndex = 1; targetIndex <= target.length; targetIndex += 1) { const substitution = source[sourceIndex - 1] === target[targetIndex - 1] ? 0 : 1; current[targetIndex] = Math.min(current[targetIndex - 1] + 1, previous[targetIndex] + 1, previous[targetIndex - 1] + substitution); if (sourceIndex > 1 && targetIndex > 1 && source[sourceIndex - 1] === target[targetIndex - 2] && source[sourceIndex - 2] === target[targetIndex - 1]) current[targetIndex] = Math.min(current[targetIndex], previousPrevious[targetIndex - 2] + 1); rowMinimum = Math.min(rowMinimum, current[targetIndex]); } if (rowMinimum > limit) return limit + 1; [previousPrevious, previous, current] = [previous, current, previousPrevious]; } return previous[target.length]; }
function fuzzyMatches(value, query) { if (value.includes(query)) return true; const threshold = /\d/u.test(query) ? 0 : query.length <= 3 ? 0 : query.length <= 6 ? 1 : 2; return threshold > 0 && [value, ...value.split(/[^\p{L}\p{N}]+/u).filter(Boolean)].some((candidate) => Math.abs(candidate.length - query.length) <= threshold && damerau(candidate, query, threshold) <= threshold); }
function regexMatches(value, pattern) { try { return new RegExp(pattern, 'iu').test(value); } catch { return false; } }
function searchValues(entry, query) { return containsHebrewLetter(query) ? [entry.Hebrew, entry.HebrewNikkud] : [entry.English, entry.Hebrew, entry.HebrewNikkud, entry.Transliteration]; }
function columnRank(values, query) { if (state.mode === 'regex') return values.some((value) => regexMatches(value || '', query)) ? 0 : Number.MAX_SAFE_INTEGER; const normalizedQuery = fold(query); let best = Number.MAX_SAFE_INTEGER; values.forEach((value) => { const normalizedValue = fold(value); const matches = state.mode === 'literal' ? normalizedValue.includes(normalizedQuery) : fuzzyMatches(normalizedValue, normalizedQuery); if (matches) best = Math.min(best, normalizedValue === normalizedQuery ? 0 : normalizedValue.startsWith(normalizedQuery) ? 1 : normalizedValue.includes(normalizedQuery) ? 2 : 3); }); return best; }
function rankedMatch(entry, query) { const englishRank = columnRank([entry.English], query); const hebrewRank = columnRank(searchValues(entry, query).filter((value) => value !== entry.English), query); if (englishRank === Number.MAX_SAFE_INTEGER && hebrewRank === Number.MAX_SAFE_INTEGER) return null; return { rank: Math.min(englishRank, hebrewRank), englishWins: state.preferEnglish ? englishRank <= hebrewRank : englishRank < hebrewRank }; }
function articleDisplay(entry) { const gender = entry.IsPluralOnly ? `${entry.Gender || ''}*` : entry.Gender || ''; return gender && entry.PersonNumber ? `${gender}, ${entry.PersonNumber}` : gender || entry.PersonNumber || ''; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/gu, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
function sortValue(entry, column) { return ({ english: entry.English || '', hebrew: entry.Hebrew || '', gender: articleDisplay(entry), category: categoryCodes[entry.LexicalClass] || '', grammar: entry.GrammarNote || '' })[column] || ''; }
function renderSortControls() { document.querySelectorAll('.sort-button').forEach((button) => { const active = button.dataset.sort === state.sortColumn; button.classList.toggle('is-active', active); if (button.dataset.sort === 'original') { button.textContent = 'Unsort'; return; } const label = button.dataset.sort === 'gender' ? 'Gen' : button.dataset.sort === 'category' ? 'Categ' : button.dataset.sort[0].toUpperCase() + button.dataset.sort.slice(1); button.textContent = `${label}${active ? state.sortDirection === 'ascending' ? ' ↑' : ' ↓' : ''}`; button.setAttribute('aria-sort', active ? state.sortDirection : 'none'); }); }
function render() { const query = input.value.trim(); let regexError = ''; let matches = state.entries.map((entry) => ({ entry, match: query ? rankedMatch(entry, query) : null })).filter(({ match }) => !query || match); if (state.mode === 'regex' && query) { if (containsHebrewLetter(query)) { regexError = 'Regex is available for English and transliteration, not Hebrew script.'; matches = []; } else { try { new RegExp(query, 'iu'); } catch (error) { regexError = error.message; matches = []; } } } const selected = query ? matches.reduce((best, current) => !best || current.match.rank < best.match.rank || (current.match.rank === best.match.rank && current.entry.Sequence < best.entry.Sequence) ? current : best, null) : null; if (state.sortColumn !== 'original') { const direction = state.sortDirection === 'ascending' ? 1 : -1; matches.sort(({ entry: left }, { entry: right }) => { const result = sortValue(left, state.sortColumn).localeCompare(sortValue(right, state.sortColumn), undefined, { sensitivity: 'base', numeric: true }); return result === 0 ? left.Sequence - right.Sequence : result * direction; }); } entriesElement.innerHTML = matches.map(({ entry }) => { const selectedClass = selected && selected.entry.Id === entry.Id ? ' selected' : ''; const transliteration = entry.Transliteration ? `<span class="transliteration">${escapeHtml(entry.Transliteration)}</span><span class="native-separator">|</span>` : ''; const nikkud = entry.HebrewNikkud ? `<span class="native-separator">|</span><span class="hebrew nikkud">${escapeHtml(entry.HebrewNikkud)}</span>` : ''; return `<div class="entry${selectedClass}" role="row" draggable="true" data-copy-text="${escapeHtml(entry.Hebrew || '')}"><span role="cell">${escapeHtml(entry.English)}</span><span class="native" role="cell">${transliteration}<span class="hebrew">${escapeHtml(entry.Hebrew)}</span>${nikkud}</span><span class="gender" role="cell">${escapeHtml(articleDisplay(entry))}</span><span class="category" role="cell">${escapeHtml(categoryCodes[entry.LexicalClass] || '')}</span><span class="grammar" role="cell" title="${escapeHtml(entry.GrammarNote || '')}">${escapeHtml(entry.GrammarNote || '')}</span></div>`; }).join(''); emptyState.hidden = matches.length > 0; searchStatus.classList.toggle('error', Boolean(regexError)); searchStatus.textContent = regexError || (query ? `${matches.length} matching ${matches.length === 1 ? 'entry' : 'entries'}` : `${state.entries.length} entries`); renderSortControls(); }
function showCopyFeedback(message, isError = false) { copyToast.textContent = message; copyToast.classList.toggle('is-error', isError); copyToast.classList.remove('is-visible'); requestAnimationFrame(() => copyToast.classList.add('is-visible')); clearTimeout(showCopyFeedback.timeout); showCopyFeedback.timeout = setTimeout(() => copyToast.classList.remove('is-visible'), 1400); }
function copyRowText(row) { const payload = row.dataset.copyText || ''; if (!payload) return; try { const clipboardWrite = navigator.clipboard.writeText(payload); row.classList.remove('copy-flash'); requestAnimationFrame(() => row.classList.add('copy-flash')); showCopyFeedback(`Copied ${payload}`); clipboardWrite.catch(() => showCopyFeedback('Copy failed', true)); } catch { showCopyFeedback('Copy failed', true); } }
entriesElement.addEventListener('dblclick', (event) => { if (Date.now() >= suppressClickUntil) { const row = event.target.closest('.entry'); if (row) copyRowText(row); } });
entriesElement.addEventListener('touchend', (event) => { const row = event.target.closest('.entry'); if (!row || event.changedTouches.length !== 1) return; const now = Date.now(); if (row === lastTouchRow && now - lastTouchTime < 300) { event.preventDefault(); suppressClickUntil = now + 500; copyRowText(row); lastTouchTime = 0; lastTouchRow = null; return; } lastTouchTime = now; lastTouchRow = row; });
entriesElement.addEventListener('dragstart', (event) => { const row = event.target.closest('.entry'); const payload = row?.dataset.copyText || ''; if (payload) event.dataTransfer.setData('text/plain', payload); });
document.querySelectorAll('.sort-button').forEach((button) => button.addEventListener('click', () => { if (button.dataset.sort === 'original') state.sortColumn = 'original'; else if (state.sortColumn === button.dataset.sort) state.sortDirection = state.sortDirection === 'ascending' ? 'descending' : 'ascending'; else { state.sortColumn = button.dataset.sort; state.sortDirection = 'ascending'; } render(); }));
document.querySelectorAll('.mode-button').forEach((button) => button.addEventListener('click', () => { state.mode = button.dataset.mode; document.querySelectorAll('.mode-button').forEach((item) => item.classList.toggle('is-active', item === button)); render(); }));
document.querySelectorAll('.language-button').forEach((button) => button.addEventListener('click', () => { state.preferEnglish = button.dataset.language === 'english'; document.querySelectorAll('.language-button').forEach((item) => item.classList.toggle('is-active', item === button)); render(); }));
input.addEventListener('focus', () => input.select());
input.addEventListener('input', render);
input.addEventListener('change', () => saveSearchTerm(input.value));
document.querySelector('#search-form').addEventListener('submit', (event) => { event.preventDefault(); saveSearchTerm(input.value); render(); });
document.querySelector('#clear-button').addEventListener('click', () => { input.value = ''; input.focus(); render(); });
const helpSections = [['Keyboard shortcuts', [['Ctrl+H', 'Open this Help window.'], ['Esc', 'Clear the search box.'], ['Double-click / double-tap', 'Copy the stored base Arabic word to the clipboard. Drag a row to paste that same word into another application.']]], ['Search modes', [['≈ Fuzzy', 'Finds close spellings and transposed letters; exact and substring matches rank first.'], ['" Literal', 'Default. Finds the entered characters as a substring. Regex punctuation has no special meaning.'], ['.* Regex', 'Uses a regular expression for English or transliteration. Arabic-script regex is unavailable.']]], ['Prefer language', [['English', 'All fields are searched. When English and Arabic matches rank equally, prefer the English match.'], ['Arabic', 'All fields are searched. When English and Arabic matches rank equally, prefer the Arabic match.']]], ['Sorting', [['Column headers', 'Select a column header to sort matching entries by that column. Select it again to reverse the order.'], ['Unsort', 'Restore the dataset\'s original order.']]], ['Regex examples (English / transliteration)', [['house', "Contains 'house'"], ['\\bhouse\\b', "Whole word 'house'"], ['small house', "Exact phrase 'small house'"], ['\\bkit\\w*', "Transliteration starts with 'kit'"], ['\\w*tab\\b', "Transliteration ends with 'tab'"], ['house|home', "Either 'house' or 'home'"], ['(?=.*small)(?=.*house)', 'Both terms, in any order'], ['colou?r', "Optional character: 'color' or 'colour'"], ['(?-i)\\bHouse\\b', 'Force case-sensitive matching']]], ['Category (Categ column)', [['N', 'Noun'], ['PN', 'Proper noun'], ['PRN', 'Pronoun'], ['ADJ', 'Adjective'], ['ADV', 'Adverb'], ['ART', 'Article'], ['D', 'Determiner'], ['PRP', 'Preposition'], ['C', 'Conjunction'], ['I', 'Interjection'], ['NM', 'Numeral'], ['PRT', 'Particle'], ['V', 'Verb']]], ['Gender / person (Gen column)', [['M', 'Masculine'], ['F', 'Feminine'], ['*', 'Plural only, shown after the gender (for example M*)'], ['1s / 2s / 3s', '1st/2nd/3rd person singular'], ['1d / 2d / 3d', '1st/2nd/3rd person dual'], ['1p / 2p / 3p', '1st/2nd/3rd person plural'], ['3ms / 3fs', 'Gender letter when the form marks it'], ['M, 3ms', 'Combined gender and person/gender/number'], ['(hover)', 'Hover truncated text to see it all']]], ['Grammar (Grammar column)', [['Pl: ...', 'Noun plural form'], ['Root: ...', "Verb's root letters"], ['Form ...', "Verb's conjugation pattern/wazn"], ['(hover)', 'Hover truncated text to see it all']]]];
const localizedHelpSections = [['Keyboard shortcuts', [['Ctrl+H', 'Open this Help window.'], ['Esc', 'Clear the search box.'], ['Double-click / double-tap', 'Copy the stored base Hebrew word to the clipboard. Drag a row to paste that same word into another application.']]], ['Search modes', [['≈ Fuzzy', 'Finds close spellings and transposed letters; exact and substring matches rank first.'], ['" Literal', 'Default. Finds the entered characters as a substring. Regex punctuation has no special meaning.'], ['.* Regex', 'Uses a regular expression for English or transliteration. Hebrew-script regex is unavailable.']]], ['Prefer language', [['English', 'All fields are searched. When English and Hebrew matches rank equally, prefer the English match.'], ['Hebrew', 'All fields are searched. When English and Hebrew matches rank equally, prefer the Hebrew match.']]], ['Sorting', [['Column headers', 'Select a column header to sort matching entries by that column. Select it again to reverse the order.'], ['Unsort', 'Restore the dataset\'s original order.']]], ['Regex examples (English / transliteration)', [['house', "Contains 'house'"], ['\\bhouse\\b', "Whole word 'house'"], ['small house', "Exact phrase 'small house'"], ['\\bkelev\\w*', "Transliteration starts with 'kelev'"], ['\\w*bayit\\b', "Transliteration ends with 'bayit'"], ['house|home', "Either 'house' or 'home'"], ['(?=.*small)(?=.*house)', 'Both terms, in any order'], ['colou?r', "Optional character: 'color' or 'colour'"], ['(?-i)\\bHouse\\b', 'Force case-sensitive matching']]], ['Category (Categ column)', [['N', 'Noun'], ['PN', 'Proper noun'], ['PRN', 'Pronoun'], ['ADJ', 'Adjective'], ['ADV', 'Adverb'], ['ART', 'Article'], ['D', 'Determiner'], ['PRP', 'Preposition'], ['C', 'Conjunction'], ['I', 'Interjection'], ['NM', 'Numeral'], ['PRT', 'Particle'], ['V', 'Verb']]], ['Gender / person (Gen column)', [['M', 'Masculine'], ['F', 'Feminine'], ['*', 'Plural only, shown after the gender (for example M*)'], ['1s / 2s / 3s', '1st/2nd/3rd person singular'], ['1p / 2p / 3p', '1st/2nd/3rd person plural'], ['3ms / 3fs', 'Gender letter when the form marks it'], ['M, 3ms', 'Combined gender and person/gender/number'], ['(hover)', 'Hover truncated text to see it all']]], ['Grammar (Grammar column)', [['Pl: ...', 'Noun plural form'], ['Root: ...', "Verb's root letters"], ['Binyan ...', "Verb's conjugation pattern"], ['(hover)', 'Hover truncated text to see it all']]]];
localizedHelpSections.push(['Hebrew columns', [['Hebrew', 'The stored base Hebrew field, copied by double-click or drag.'], ['Nikkud', 'The fully vocalized Hebrew display value when available.'], ['Transliteration', 'Latin transliteration used for normal search and regex matching.']]]);
function renderHelp() { document.querySelector('#help-sections').innerHTML = localizedHelpSections.map(([title, entries]) => `<section class="help-section"><h3>${escapeHtml(title)}</h3>${entries.map(([code, meaning]) => `<p class="help-entry"><strong>${escapeHtml(code)}</strong><span>${escapeHtml(meaning)}</span></p>`).join('')}</section>`).join(''); }
const helpDialog = document.querySelector('#help-dialog');
function openHelp() { helpDialog.hidden = false; document.body.classList.add('modal-open'); }
function closeHelp() { helpDialog.hidden = true; document.body.classList.remove('modal-open'); }
document.querySelector('#help-button').addEventListener('click', openHelp);
document.querySelector('#close-help-button').addEventListener('click', closeHelp);
document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !helpDialog.hidden) { closeHelp(); return; } if (event.key === 'Escape') { input.value = ''; render(); } if (event.ctrlKey && event.key.toLowerCase() === 'h') { event.preventDefault(); openHelp(); } });
loadSearchHistory(); renderHelp();
fetch('vocabulary.json').then((response) => { if (!response.ok) throw new Error(`Could not load vocabulary (${response.status})`); return response.json(); }).then((data) => { state.entries = data.sort((left, right) => (right.Sequence ?? 0) - (left.Sequence ?? 0)); datasetStatus.textContent = `${state.entries.length}`; statusDot.classList.add('ready'); render(); }).catch((error) => { datasetStatus.textContent = 'Vocabulary unavailable'; searchStatus.textContent = error.message; searchStatus.classList.add('error'); });